/**
 * Generates THIRD-PARTY-NOTICES.md for the packages bundled into bin/plugin.js.
 *
 * This file used to be written by hand, and it went wrong in both of the ways a
 * hand-written notice file does: it named versions the lockfile had moved past,
 * and it missed a package entirely. Since the notice is the thing that makes
 * redistributing the packed plugin lawful, "probably still accurate" is not good
 * enough.
 *
 * So it is derived instead. The package list comes from the lockfile's non-dev
 * entries -- those, and only those, are what rollup can pull into the bundle --
 * and each licence text is copied out of the installed package rather than
 * transcribed. A package with no licence file stops the build rather than
 * shipping a notice with a hole in it.
 */

import { readdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

/** Reads the licence text a package ships, whatever it chose to call the file. */
async function licenceOf(name) {
	const dir = join(root, "node_modules", name);
	let entries;
	try {
		entries = await readdir(dir);
	} catch {
		throw new Error(`notices: ${name} is in the lockfile but not installed -- run \`npm ci\` first`);
	}

	const file = entries.find((entry) => /^licen[sc]e(\.|$)/i.test(entry));
	if (file === undefined) {
		throw new Error(
			`notices: ${name} ships no licence file, so its terms cannot be reproduced.\n` +
				`  Look it up and add it by hand, or drop the dependency.`,
		);
	}

	// Normalised to LF: these texts come from packages published on every kind of
	// machine, and a CRLF one would be the only file in the repository with mixed
	// endings, which is exactly the diff noise .gitattributes exists to prevent.
	return (await readFile(join(dir, file), "utf8")).replace(/\r\n/g, "\n").trim();
}

const lock = JSON.parse(await readFile(join(root, "package-lock.json"), "utf8"));

// Anything marked dev is build tooling -- rollup, sharp, typescript. It runs on
// the machine doing the building and never reaches a user, so it is not part of
// what gets redistributed.
const bundled = Object.entries(lock.packages ?? {})
	.filter(([path, entry]) => path.startsWith("node_modules/") && !entry.dev)
	.map(([path, entry]) => ({ name: path.replace(/^node_modules\//, ""), version: entry.version }))
	.sort((a, b) => a.name.localeCompare(b.name));

if (bundled.length === 0) throw new Error("notices: the lockfile lists no runtime dependencies -- that cannot be right");

const sections = [];
for (const { name, version } of bundled) {
	sections.push(`## ${name} ${version}\n\n${await licenceOf(name)}`);
}

const notices =
	`# Third-party notices\n\n` +
	`\`bin/plugin.js\` is a bundle. The build inlines the packages below and the\n` +
	`minifier strips their comments, so their copyright notices cannot survive inside\n` +
	`the file itself -- they are reproduced here instead, which is what their licences\n` +
	`require of anyone redistributing the packed plugin.\n\n` +
	`This file lives inside the \`.sdPlugin\` folder on purpose: \`npm run pack\` ships\n` +
	`whatever is in that folder, so the notices travel with the \`.streamDeckPlugin\`.\n\n` +
	`Generated by \`scripts/build-notices.mjs\` from \`package-lock.json\` and the\n` +
	`licence files of the installed packages. Do not edit it by hand -- update the\n` +
	`dependencies and rebuild.\n\n` +
	`---\n\n${sections.join("\n\n---\n\n")}\n\n---\n\n` +
	`## mulberry32\n\n` +
	`The seeded PRNG in \`scripts/art.mjs\` is Tommy Ettinger's mulberry32, released\n` +
	`into the public domain. It is a build-time dependency only and is not part of\n` +
	`the shipped bundle.\n`;

const plugin = (await readdir(root)).find((entry) => entry.endsWith(".sdPlugin"));
await writeFile(join(root, plugin, "THIRD-PARTY-NOTICES.md"), notices, "utf8");

console.log(`notices: ${bundled.length} bundled packages -> ${plugin}/THIRD-PARTY-NOTICES.md`);
for (const { name, version } of bundled) console.log(`  ${name} ${version}`);
